services:
  - type: web
    name: coursenest-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install && npm run seed
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
